name: CI
on:
  workflow_dispatch:
  push:
    branches:
      - stable

jobs:
  info:
    runs-on: ubuntu-20.04
    outputs: 
      version: ${{ steps.regex-match.outputs.group1 }}
    steps:
      - uses: actions/checkout@v3
      - id: cat-cmake
        run: |
          echo "camkelists=$(cat CMakeLists.txt)" >> $OUTPUT
      - uses: actions-ecosystem/action-regex-match@v2
        id: regex-match
        with:
          text: ${{ steps.cat-cmake.outputs.camkelists }}
          regex: '(?>project\(.*VERSION *")(\d.\d.\d)(?>".*\))'
          flags: 'gm'

  build-arm64:
    # noinspection YAMLSchemaValidation
    runs-on: buildjet-2vcpu-ubuntu-2204-arm
    needs: info
    steps:
      # Dependencies
      - uses: awalsh128/cache-apt-pkgs-action@latest
        with:
          packages: cmake libgl1-mesa-dev libgles2-mesa-dev libegl1-mesa-dev libdrm-dev libgbm-dev ttf-mscorefonts-installer fontconfig libsystemd-dev libinput-dev libudev-dev  libxkbcommon-dev
          version: 1.0
      - run: |
          fc-cache

      # Build
      - uses: actions/checkout@v3
      - name: "Build"
        run: |
          mkdir build && cd build
          cmake ..
          cmake --build .
          cpack
      - uses: actions/upload-artifact@v3
        with:
          name: deb-arm64
          path: build/*.deb
  release-ppa:
    runs-on: ubuntu-20.04
    needs:
      - info
      - build-arm64
    steps:
      - uses: actions/checkout@v4
        with:
          repositry: "fotobox-ms/ppa"
      - uses: actions/download-artifact@v3
        with:
          name: deb-arm64
      - run: |
          git commit -m "(CI) updated ppa with flutter-pi packages"
          git push
  release-github:
    runs-on: ubuntu-20.04
    needs:
      - info
      - build-arm64
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: deb-arm64
      - uses: ncipollo/release-action@v1
        with:
          artifacts: "*"
          allowUpdates: true
          tag: v${{ needs.info.outputs.version }}
          
      
